[package]
name = "reverse_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
serde = { version = "1.0.159", features = ["serde_derive", "rc"] }
serde_json = "1.0"
good_lp = { version = "1.7.0", features = ["lpsolve"], default-features = true }
anyhow = "1.0"
log = "0.4"
simplelog = "0.12.2"
ndarray = { version = "0.15.6", features = ["serde"] } 
ndarray-rand = "0.14.0"
ndarray-stats = "0.5.1"
ndarray-linalg = "0.16.0"
itertools = "0.12.1"